package com.mpsilvestri.api;

public class XML {
	
	String api_key;
	int server;
	String url;
	
	String table;
	String field;
	String search_text;
	
	String operator;
	
	String xml;

	public XML(String api_key, int server, String url, String table, String field, String search_text) {
		
		this.api_key = api_key;
		this.server = server;
		this.url = url;
		this.table = table;
		this.field = field;
		this.search_text = search_text;		
		
	}
	
	// ==> to continue programming this method with all XML's and detected the issue with IsActive (it does not accept operator Equals)
	public String generate_xml() {
		
		if(table.equalsIgnoreCase("Sku")) {
			if(field.equalsIgnoreCase("ProductName")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>ProductName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Price</Column>\r\n"
						+ "\r\n"
						+ "        <Column>ListPrice</Column>\r\n"
						+ "\r\n"
						+ "        <Column>IsActive</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>ProductName</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Ascending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("IsActive")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>ProductName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Price</Column>\r\n"
						+ "\r\n"
						+ "        <Column>ListPrice</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Equals</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>ProductName</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Ascending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				return this.xml;
			}
		}
		
		if(table.equalsIgnoreCase("Order")) {
			if(field.equalsIgnoreCase("Status")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>FirstName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>LastName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Email</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Phone</Column>\r\n"
						+ "\r\n"
						+ "        <Column>CreationDate</Column>\r\n"
						+ "\r\n"
						+ "        <Column>PaymentSystemName</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>CreationDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("FirstName")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>Email</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Phone</Column>\r\n"
						+ "\r\n"
						+ "        <Column>LastName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>CreationDate</Column>\r\n"
						+ "\r\n"
						+ "        <Column>PaymentSystemName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Status</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>CreationDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("Email")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>FirstName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>LastName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Phone</Column>\r\n"
						+ "\r\n"
						+ "        <Column>CreationDate</Column>\r\n"
						+ "\r\n"
						+ "        <Column>PaymentSystemName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Status</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Equals</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>CreationDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("CreationDate")) { // <<-- Error: HTTP Error 411. The request must be chunked or have a content length.
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>FirstName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>LastName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Email</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Phone</Column>\r\n"
						+ "\r\n"
						+ "        <Column>PaymentSystemName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Status</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Equals</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>Status</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Ascending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("PaymentSystemName")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>FirstName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>LastName</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Email</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Phone</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Status</Column>\r\n"
						+ "\r\n"
						+ "        <Column>CreationDate</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Equals</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>CreationDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			}
		}
		
		if(table.equalsIgnoreCase("Product")) {
			if(field.equalsIgnoreCase("Name")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>Name</Column>\r\n"
						+ "\r\n"
						+ "        <Column>ReleaseDate</Column>\r\n"
						+ "\r\n"
						+ "        <Column>IsActive</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>ReleaseDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("Description")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>Name</Column>\r\n"
						+ "\r\n"
						+ "        <Column>ReleaseDate</Column>\r\n"
						+ "\r\n"
						+ "        <Column>IsActive</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>ReleaseDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("ReleaseDate")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>Name</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Description</Column>\r\n"
						+ "\r\n"
						+ "        <Column>IsActive</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Equals</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>ReleaseDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} else if(field.equalsIgnoreCase("IsActive")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>Name</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Description</Column>\r\n"
						+ "\r\n"
						+ "        <Column>ReleaseDate</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>ReleaseDate</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Descending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} 
		}
		
		if(table.equalsIgnoreCase("Category")) {
			if(field.equalsIgnoreCase("Name")) {
				this.xml = "<ApiRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n"
						+ "\r\n"
						+ "    <ApiKey>"+this.api_key+"</ApiKey>\r\n"
						+ "\r\n"
						+ "    <TableName>"+this.table+"</TableName>\r\n"
						+ "\r\n"
						+ "    <Columns>\r\n"
						+ "\r\n"
						+ "        <Column>Name</Column>\r\n"
						+ "\r\n"
						+ "        <Column>Title</Column>\r\n"
						+ "\r\n"
						+ "    </Columns>\r\n"
						+ "\r\n"
						+ "    <WhereConditions>\r\n"
						+ "\r\n"
						+ "         <Where>\r\n"
						+ "\r\n"
						+ "             <ColumnName>"+this.field+"</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Operator>Like</Operator>\r\n"
						+ "\r\n"
						+ "             <Value>"+this.search_text+"</Value>\r\n"
						+ "\r\n"
						+ "         </Where>\r\n"
						+ "\r\n"
						+ "    </WhereConditions>\r\n"
						+ "\r\n"
						+ "    <OrderByColumns>\r\n"
						+ "\r\n"
						+ "         <OrderBy>\r\n"
						+ "\r\n"
						+ "             <ColumnName>Title</ColumnName>\r\n"
						+ "\r\n"
						+ "             <Direction>Ascending</Direction>\r\n"
						+ "\r\n"
						+ "         </OrderBy>\r\n"
						+ "\r\n"
						+ "    </OrderByColumns>\r\n"
						+ "\r\n"
						+ "    <Limit>50</Limit>\r\n"
						+ "\r\n"
						+ "</ApiRequest>";
				
				return this.xml;
			} 
		}
		
		return "";
	}

}
